# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='type',
            field=models.CharField(default='std', max_length=3),
            preserve_default=False,
        ),
    ]
