# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_is_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_stuff',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
