# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='/logo/')),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('field', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
