# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20160925_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
    ]
