# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=50)),
                ('cirtifications', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to=b'')),
                ('website', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
