# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='descripton',
            field=models.TextField(blank=True, null=True),
        ),
    ]
