# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20160925_0551'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employer.CompanyProfile'),
            preserve_default=False,
        ),
    ]
