# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('job', '0002_jobpost_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to=b'')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobPost')),
            ],
        ),
    ]
